#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
waf00.py — Advanced WAF/Firewall Detection Tool
====================================================
Multi-layer detection engine:
  Layer 1: Passive fingerprinting  (headers, cookies, server tokens)
  Layer 2: Active payload probing  (rate-limited, evasion-aware)
  Layer 3: Behavioral diffing      (normal vs suspicious response delta)
  Layer 4: Confidence scoring      (weighted signals → 0-100% confidence)

Overcomes WAFW00F limitations:
  - Outdated sigs      → behavioral analysis works on unknown WAFs
  - False pos/neg      → confidence scoring with multiple independent signals
  - IP blocking        → randomised delays, user-agents, and request spacing
  - Custom WAFs        → body/timing/status-code delta catches them all

Usage:
  python waf00.py <target> [options]
  python waf00.py https://example.com -v --report report.json
"""

import argparse
import json
import os
import random
import re
import sys
import time
import urllib.parse
from dataclasses import dataclass, field, asdict
from typing import Optional

try:
    import requests
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
except ImportError:
    print("[!] Missing dependency: pip install requests")
    sys.exit(1)

# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS & CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
VERSION = "1.0.0"
TOOL_NAME = "waf00"

DEFAULT_TIMEOUT = 10          # seconds per request
MIN_DELAY       = 0.8         # minimum seconds between probes
MAX_DELAY       = 2.5         # maximum seconds between probes (avoids IP ban)
MAX_RETRIES     = 2


# Rotating user-agents to avoid fingerprinting the scanner itself
USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/124.0.0.0",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
]

# ─────────────────────────────────────────────────────────────────────────────
# WAF SIGNATURE DATABASE
# Each entry: name, confidence_weight, and lists of signals to match against
#   headers        → dict key:regex_pattern (checked against response headers)
#   cookies        → list of cookie name patterns
#   body_patterns  → list of regex patterns checked in response body
#   status_codes   → list of HTTP status codes that are strong indicators
# ─────────────────────────────────────────────────────────────────────────────
WAF_SIGNATURES = [
    {
        "name": "Cloudflare",
        "headers": {
            "server": r"cloudflare",
            "cf-ray": r".+",
            "cf-cache-status": r".+",
            "cf-request-id": r".+",
        },
        "cookies": [r"^__cflb$", r"^cf_clearance$", r"^__cf_bm$"],
        "body_patterns": [
            r"cloudflare",
            r"Attention Required! \| Cloudflare",
            r"cf-browser-verification",
            r"Ray ID:?\s*[0-9a-f]{16}",
        ],
        "status_codes": [403, 429, 503],
        "weight": 35,
    },
    {
        "name": "AWS WAF / CloudFront",
        "headers": {
            "x-amz-cf-id": r".+",
            "x-amzn-requestid": r".+",
            "x-amzn-trace-id": r".+",
            "via": r"CloudFront",
            "server": r"AmazonS3|CloudFront",
        },
        "cookies": [r"^AWSALB$", r"^AWSALBCORS$", r"^AWSELB$"],
        "body_patterns": [
            r"AWS CloudFront",
            r"Generated by cloudfront",
            r"ERROR: The request could not be satisfied",
            r"Request blocked",
        ],
        "status_codes": [403, 400],
        "weight": 35,
    },
    {
        "name": "Akamai",
        "headers": {
            "x-akamai-transformed": r".+",
            "x-akamai-request-id": r".+",
            "x-check-cacheable": r".+",
            "akamai-origin-hop": r".+",
            "x-akamai-ssl-client-sid": r".+",
        },
        "cookies": [r"^ak_bmsc$", r"^bm_sz$", r"^bm_sv$"],
        "body_patterns": [
            r"akamai",
            r"The requested URL was rejected",
            r"Reference #\d+\.\w+\.\d+",
            r"Access Denied.*Akamai",
        ],
        "status_codes": [403, 400],
        "weight": 35,
    },
    {
        "name": "Imperva / Incapsula",
        "headers": {
            "x-iinfo": r".+",
            "x-cdn": r"Incapsula",
            "x-sucuri-id": r".+",
        },
        "cookies": [r"^incap_ses", r"^visid_incap", r"^nlbi_"],
        "body_patterns": [
            r"Incapsula incident ID",
            r"incapsula",
            r"/_Incapsula_Resource",
            r"Request unsuccessful\. Incapsula incident",
        ],
        "status_codes": [403, 401],
        "weight": 35,
    },
    {
        "name": "Sucuri",
        "headers": {
            "x-sucuri-id": r".+",
            "x-sucuri-cache": r".+",
            "server": r"Sucuri/Cloudproxy",
        },
        "cookies": [],
        "body_patterns": [
            r"Sucuri Website Firewall",
            r"sucuri\.net",
            r"Access Denied - Sucuri",
            r"cloudproxy\.sucuri\.net",
        ],
        "status_codes": [403, 500],
        "weight": 35,
    },
    {
        "name": "F5 BIG-IP ASM",
        "headers": {
            "server": r"BigIP|BIG-IP|F5",
            "x-cnection": r".+",
            "set-cookie": r"BIGipServer",
        },
        "cookies": [r"^BIGipServer", r"^TS[0-9a-f]{8}"],
        "body_patterns": [
            r"BIG-IP",
            r"The requested URL was rejected",
            r"Please consult with your administrator",
            r"Reference ID:\s+[\w.]+",
            r"ASM:.*blocked",
        ],
        "status_codes": [403, 400],
        "weight": 35,
    },
    {
        "name": "Fortinet FortiWeb",
        "headers": {
            "server": r"FortiWeb",
            "fortiwafsid": r".+",
        },
        "cookies": [r"^FORTIWAFSID"],
        "body_patterns": [
            r"FortiWeb",
            r"Server Unavailable",
            r"Powered by FortiWeb",
            r"Your request has been blocked by FortiWeb",
        ],
        "status_codes": [403, 503],
        "weight": 35,
    },
    {
        "name": "Barracuda WAF",
        "headers": {
            "server": r"Barracuda",
            "x-barracuda-id": r".+",
        },
        "cookies": [r"^barra_counter_session", r"^BNI__BARRACUDA_LB_COOKIE"],
        "body_patterns": [
            r"barracuda",
            r"Barracuda Networks",
            r"You have been blocked",
            r"barra_counter_session",
        ],
        "status_codes": [403, 400],
        "weight": 35,
    },
    {
        "name": "Radware AppWall",
        "headers": {
            "x-sl-compstate": r".+",
            "server": r"Radware",
        },
        "cookies": [r"^RADWARE_SESSION"],
        "body_patterns": [
            r"Radware",
            r"AppWall",
            r"The page cannot be displayed.*Radware",
            r"RDWR",
        ],
        "status_codes": [403, 400],
        "weight": 35,
    },
    {
        "name": "Nginx ModSecurity / Generic ModSecurity",
        "headers": {
            "server": r"mod_security|ModSecurity|NOYB",
        },
        "cookies": [],
        "body_patterns": [
            r"ModSecurity",
            r"This error was generated by Mod_Security",
            r"406 Not Acceptable",
            r"Not Acceptable!.*Apache",
            r"Mod Security",
        ],
        "status_codes": [406, 403, 501],
        "weight": 30,
    },
    {
        "name": "Wordfence (WordPress WAF)",
        "headers": {},
        "cookies": [r"^wfvt_", r"^wordfence_verifiedHuman"],
        "body_patterns": [
            r"Generated by Wordfence",
            r"wordfence\.com",
            r"Your access to this site has been limited",
            r"Wordfence",
            r"wf-blocking-page",
        ],
        "status_codes": [403, 503],
        "weight": 30,
    },
    {
        "name": "Fastly",
        "headers": {
            "x-fastly-request-id": r".+",
            "fastly-restarts": r".+",
            "x-served-by": r"cache-",
            "x-cache": r"HIT|MISS",
            "x-cache-hits": r".+",
        },
        "cookies": [],
        "body_patterns": [
            r"Fastly error",
            r"fastly\.com",
            r"Varnish cache server",
        ],
        "status_codes": [403, 503],
        "weight": 25,
    },
    {
        "name": "Nginx / Generic CDN WAF",
        "headers": {
            "server": r"^nginx$",
            "x-cache": r"MISS|HIT",
        },
        "cookies": [],
        "body_patterns": [
            r"<title>403 Forbidden</title>",
            r"nginx.*blocked",
        ],
        "status_codes": [403],
        "weight": 10,  # low weight — nginx alone is not conclusive
    },
    {
        "name": "Alibaba Cloud WAF",
        "headers": {
            "server": r"Tengine",
            "x-swift-savetime": r".+",
            "x-cache": r".+",
        },
        "cookies": [r"^aliyungf_tc"],
        "body_patterns": [
            r"error\.aliyuncs\.com",
            r"阿里云",
            r"Alibaba Cloud",
            r"Your request has been blocked",
        ],
        "status_codes": [403, 405],
        "weight": 35,
    },
    {
        "name": "StackPath / MaxCDN",
        "headers": {
            "x-sp-waf": r".+",
            "server": r"StackPath",
        },
        "cookies": [],
        "body_patterns": [
            r"StackPath",
            r"stackpath\.com",
            r"MaxCDN",
        ],
        "status_codes": [403],
        "weight": 30,
    },
    {
        "name": "Reblaze",
        "headers": {
            "x-reblaze-protection": r".+",
            "server": r"reblaze",
        },
        "cookies": [r"^rbzid", r"^rbzsessionid"],
        "body_patterns": [r"reblaze", r"Access Denied.*Reblaze"],
        "status_codes": [403],
        "weight": 35,
    },
    {
        "name": "DataPower (IBM)",
        "headers": {
            "x-backside-transport": r".+",
            "x-powered-by": r"IBM_HTTP_Server",
        },
        "cookies": [],
        "body_patterns": [r"DataPower", r"IBM DataPower", r"dp-block"],
        "status_codes": [403],
        "weight": 35,
    },
    {
        "name": "Microsoft Azure Front Door / WAF",
        "headers": {
            "x-azure-ref": r".+",
            "x-ms-request-id": r".+",
            "x-fd-healthprobe": r".+",
        },
        "cookies": [],
        "body_patterns": [
            r"Azure Front Door",
            r"microsoft\.com.*blocked",
            r"The request is blocked",
        ],
        "status_codes": [403, 400],
        "weight": 35,
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# ACTIVE PROBE PAYLOADS
# These are sent one at a time with delays between them.
# Each payload is designed to trigger a WAF while being minimally invasive.
# We never exploit — we only probe for detection reactions.
# ─────────────────────────────────────────────────────────────────────────────
PROBE_PAYLOADS = [
    # Classic XSS probe
    {"path": "/?x=<script>alert(1)</script>", "type": "xss",         "desc": "XSS probe"},
    # SQLi probe
    {"path": "/?id=1'%20OR%20'1'='1", "type": "sqli",               "desc": "SQLi OR probe"},
    {"path": "/?id=1;DROP%20TABLE%20users", "type": "sqli",          "desc": "SQLi DROP probe"},
    # Path traversal
    {"path": "/?file=../../etc/passwd",       "type": "traversal",    "desc": "Path traversal probe"},
    {"path": "/?file=..%2F..%2Fetc%2Fshadow", "type": "traversal",   "desc": "Encoded traversal probe"},
    # Command injection
    {"path": "/?cmd=;ls%20-la",               "type": "cmdi",        "desc": "Command injection probe"},
    # Scanner/tool detection header
    {"path": "/",                             "type": "header_probe", "desc": "Suspicious UA probe",
     "extra_headers": {"User-Agent": "Nikto/2.1.6 (Evasion: None)", "X-Scanner": "true"}},
    # Invalid HTTP method probe
    {"path": "/",                             "type": "method_probe", "desc": "Invalid method probe",
     "method": "INVALID"},
    # Long URL probe
    {"path": "/?" + "A" * 2048,              "type": "overflow",     "desc": "Long URL buffer probe"},
    # Null byte probe
    {"path": "/?x=test%00.php",               "type": "nullbyte",    "desc": "Null byte probe"},
]

# Generic WAF block indicators (for unknown/custom WAFs)
GENERIC_BLOCK_PATTERNS = [
    r"access denied",
    r"blocked",
    r"forbidden",
    r"your (ip|request|access) (has been|is) (blocked|denied|restricted)",
    r"security policy",
    r"suspicious activity",
    r"automated (request|traffic|access)",
    r"please verify you are a human",
    r"ddos protection",
    r"rate limit",
    r"too many requests",
    r"captcha",
    r"i2m+ybgkhqpqbq",   # common WAF challenge token pattern
]

# HTTP status codes strongly associated with WAF blocks
BLOCK_STATUS_CODES = {403, 406, 429, 503, 400, 412, 418, 401}


# ─────────────────────────────────────────────────────────────────────────────
# DATA CLASSES
# ─────────────────────────────────────────────────────────────────────────────
@dataclass
class ProbeResult:
    """Stores result of a single HTTP probe."""
    url: str
    method: str
    status_code: int
    response_time: float          # seconds
    headers: dict
    body_snippet: str             # first 2000 chars of body
    cookies: dict
    error: Optional[str] = None

@dataclass
class DetectionSignal:
    """A single detection signal with its source and weight."""
    layer: str                    # passive | active | behavioral
    signal_type: str              # header | cookie | body | status | timing | delta
    detail: str                   # human-readable description
    matched_waf: Optional[str]    # specific WAF name if matched, else None
    confidence_contribution: int  # 0-100 points added to overall score

@dataclass
class DetectionReport:
    """Full detection report for a target."""
    target: str
    scan_time: str
    waf_detected: bool
    waf_names: list = field(default_factory=list)
    confidence: int = 0           # 0-100
    verdict: str = ""
    signals: list = field(default_factory=list)
    baseline: dict = field(default_factory=dict)
    probe_summary: dict = field(default_factory=dict)
    recommendations: list = field(default_factory=list)
    raw_headers: dict = field(default_factory=dict)


# ─────────────────────────────────────────────────────────────────────────────
# HTTP CLIENT
# ─────────────────────────────────────────────────────────────────────────────
class HTTPClient:
    """
    Thin requests wrapper that handles:
      - Random User-Agent rotation
      - Configurable delays between requests (IP ban avoidance)
      - Retry logic for transient errors
      - SSL verification toggle
    """

    def __init__(self, timeout: int = DEFAULT_TIMEOUT, verify_ssl: bool = False,
                 proxy: Optional[str] = None, delay: bool = True):
        self.timeout  = timeout
        self.verify   = verify_ssl
        self.proxy    = {"http": proxy, "https": proxy} if proxy else None
        self.delay    = delay
        self.session  = requests.Session()
        # Common browser headers to blend in
        self.session.headers.update({
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate",
            "Connection": "keep-alive",
            "Upgrade-Insecure-Requests": "1",
        })

    def _rotate_ua(self):
        self.session.headers["User-Agent"] = random.choice(USER_AGENTS)

    def _sleep(self):
        if self.delay:
            time.sleep(random.uniform(MIN_DELAY, MAX_DELAY))

    def get(self, url: str, extra_headers: dict = None,
            method: str = "GET") -> ProbeResult:
        self._rotate_ua()
        self._sleep()
        headers = dict(self.session.headers)
        if extra_headers:
            headers.update(extra_headers)

        start = time.time()
        for attempt in range(MAX_RETRIES + 1):
            try:
                if method == "GET":
                    resp = self.session.get(
                        url, headers=headers, timeout=self.timeout,
                        verify=self.verify, proxies=self.proxy,
                        allow_redirects=True
                    )
                else:
                    resp = self.session.request(
                        method, url, headers=headers, timeout=self.timeout,
                        verify=self.verify, proxies=self.proxy,
                        allow_redirects=True
                    )
                elapsed = time.time() - start
                body = ""
                try:
                    body = resp.text[:2000]
                except Exception:
                    pass
                cookies = {c.name: c.value for c in resp.cookies}
                return ProbeResult(
                    url=url, method=method,
                    status_code=resp.status_code,
                    response_time=round(elapsed, 3),
                    headers=dict(resp.headers),
                    body_snippet=body,
                    cookies=cookies,
                )
            except requests.exceptions.SSLError:
                # retry without SSL verify
                self.verify = False
                if attempt == MAX_RETRIES:
                    return ProbeResult(url=url, method=method, status_code=0,
                                       response_time=0, headers={},
                                       body_snippet="", cookies={},
                                       error="SSL error")
            except requests.exceptions.ConnectionError as e:
                if attempt == MAX_RETRIES:
                    return ProbeResult(url=url, method=method, status_code=0,
                                       response_time=0, headers={},
                                       body_snippet="", cookies={},
                                       error=f"Connection error: {e}")
                time.sleep(1)
            except requests.exceptions.Timeout:
                elapsed = time.time() - start
                return ProbeResult(url=url, method=method, status_code=0,
                                   response_time=round(elapsed, 3), headers={},
                                   body_snippet="", cookies={},
                                   error="Timeout")
            except Exception as e:
                return ProbeResult(url=url, method=method, status_code=0,
                                   response_time=0, headers={},
                                   body_snippet="", cookies={},
                                   error=str(e))


# ─────────────────────────────────────────────────────────────────────────────
# LAYER 1 — PASSIVE FINGERPRINTING
# ─────────────────────────────────────────────────────────────────────────────
class PassiveDetector:
    """
    Analyses a single normal response for WAF artifacts without sending
    any suspicious payloads. Zero risk of triggering blocks.

    Checks:
      - HTTP response headers against known WAF header signatures
      - Cookie names against known WAF cookie patterns
      - Response body against known WAF body patterns
    """

    def analyse(self, result: ProbeResult) -> list:
        """Returns a list of DetectionSignal."""
        signals = []
        if result.error:
            return signals

        h_lower = {k.lower(): v.lower() for k, v in result.headers.items()}
        body_lower = result.body_snippet.lower()

        for sig in WAF_SIGNATURES:
            matched_signals = []

            # ── Header matching ──────────────────────────────────────────────
            for header_name, pattern in sig.get("headers", {}).items():
                val = h_lower.get(header_name.lower(), "")
                if val and re.search(pattern, val, re.IGNORECASE):
                    matched_signals.append(
                        DetectionSignal(
                            layer="passive",
                            signal_type="header",
                            detail=f"Header '{header_name}: {result.headers.get(header_name, val)}' matches {sig['name']}",
                            matched_waf=sig["name"],
                            confidence_contribution=sig["weight"],
                        )
                    )

            # ── Cookie matching ──────────────────────────────────────────────
            for cookie_pattern in sig.get("cookies", []):
                for cookie_name in result.cookies:
                    if re.search(cookie_pattern, cookie_name, re.IGNORECASE):
                        matched_signals.append(
                            DetectionSignal(
                                layer="passive",
                                signal_type="cookie",
                                detail=f"Cookie '{cookie_name}' matches {sig['name']}",
                                matched_waf=sig["name"],
                                confidence_contribution=sig["weight"],
                            )
                        )
                        break

            # ── Body pattern matching ────────────────────────────────────────
            for body_pat in sig.get("body_patterns", []):
                if re.search(body_pat, body_lower, re.IGNORECASE):
                    matched_signals.append(
                        DetectionSignal(
                            layer="passive",
                            signal_type="body",
                            detail=f"Body matches pattern '{body_pat}' for {sig['name']}",
                            matched_waf=sig["name"],
                            confidence_contribution=sig["weight"],
                        )
                    )
                    break  # one body match per sig is enough

            signals.extend(matched_signals)

        # ── Generic security headers (vendor-neutral WAF hint) ───────────────
        security_headers = [
            "x-waf-event-info", "x-protected-by", "x-firewall-protection",
            "x-security-action", "x-iinfo", "x-rack-cache",
        ]
        for sh in security_headers:
            if sh in h_lower:
                signals.append(DetectionSignal(
                    layer="passive",
                    signal_type="header",
                    detail=f"Generic security header found: '{sh}: {h_lower[sh]}'",
                    matched_waf=None,
                    confidence_contribution=20,
                ))

        return signals


# ─────────────────────────────────────────────────────────────────────────────
# LAYER 2 — ACTIVE PROBE DETECTION
# ─────────────────────────────────────────────────────────────────────────────
class ActiveDetector:
    """
    Sends crafted payloads one at a time with randomized delays.
    For each probe response, checks:
      - Status code against known block codes
      - Body against known WAF block messages + generic block patterns
      - Header changes compared to baseline
    Tracks aggregate probe statistics for behavioral analysis.
    """

    def __init__(self, client: HTTPClient, base_url: str, verbose: bool = False):
        self.client   = client
        self.base_url = base_url.rstrip("/")
        self.verbose  = verbose

    def run_probes(self, baseline: ProbeResult) -> tuple:
        """
        Returns (signals: list[DetectionSignal], probe_results: list[ProbeResult])
        """
        signals      = []
        probe_results = []

        for probe in PROBE_PAYLOADS:
            url = self.base_url + probe["path"]
            method = probe.get("method", "GET")
            extra_h = probe.get("extra_headers", {})

            if self.verbose:
                _print_dim(f"  → Probing [{probe['type']}] {probe['desc']} ...")

            result = self.client.get(url, extra_headers=extra_h, method=method)
            probe_results.append(result)

            if result.error:
                if self.verbose:
                    _print_dim(f"     ✗ Error: {result.error}")
                continue

            found_signals = self._analyse_probe_response(result, baseline, probe)
            signals.extend(found_signals)

            if self.verbose and found_signals:
                for s in found_signals:
                    _print_yellow(f"     ⚡ Signal [{s.signal_type}]: {s.detail}")

        return signals, probe_results

    def _analyse_probe_response(self, result: ProbeResult,
                                 baseline: ProbeResult, probe: dict) -> list:
        signals = []
        body_lower = result.body_snippet.lower()

        # ── Known WAF block body patterns ────────────────────────────────────
        for sig in WAF_SIGNATURES:
            for body_pat in sig.get("body_patterns", []):
                if re.search(body_pat, body_lower, re.IGNORECASE):
                    signals.append(DetectionSignal(
                        layer="active",
                        signal_type="body",
                        detail=f"Probe '{probe['desc']}' triggered {sig['name']} block page",
                        matched_waf=sig["name"],
                        confidence_contribution=sig["weight"],
                    ))
                    break

        # ── Generic block body patterns ──────────────────────────────────────
        for pat in GENERIC_BLOCK_PATTERNS:
            if re.search(pat, body_lower, re.IGNORECASE):
                signals.append(DetectionSignal(
                    layer="active",
                    signal_type="body",
                    detail=f"Probe '{probe['desc']}' → generic block body pattern: '{pat}'",
                    matched_waf=None,
                    confidence_contribution=25,
                ))
                break

        # ── Block status code ────────────────────────────────────────────────
        if result.status_code in BLOCK_STATUS_CODES and baseline.status_code not in BLOCK_STATUS_CODES:
            signals.append(DetectionSignal(
                layer="active",
                signal_type="status",
                detail=f"Probe '{probe['desc']}' → status {result.status_code} (baseline was {baseline.status_code})",
                matched_waf=None,
                confidence_contribution=30,
            ))

        # ── New headers appeared after probe (WAF injection) ─────────────────
        baseline_keys = {k.lower() for k in baseline.headers}
        probe_keys    = {k.lower() for k in result.headers}
        new_headers   = probe_keys - baseline_keys
        suspicious_new = [h for h in new_headers if any(
            kw in h for kw in ["waf", "firewall", "security", "block", "cf-", "x-amz", "incap", "akamai"]
        )]
        for h in suspicious_new:
            signals.append(DetectionSignal(
                layer="active",
                signal_type="header",
                detail=f"Probe '{probe['desc']}' injected new header: '{h}'",
                matched_waf=None,
                confidence_contribution=20,
            ))

        return signals


# ─────────────────────────────────────────────────────────────────────────────
# LAYER 3 — BEHAVIORAL ANALYSIS
# ─────────────────────────────────────────────────────────────────────────────
class BehavioralAnalyzer:
    """
    This is the key differentiator over WAFW00F.

    Instead of purely matching known signatures, it measures HOW the server
    BEHAVES differently when receiving suspicious vs normal requests.

    Metrics:
      - Body length delta: WAFs often return very different body sizes
      - Response time delta: WAFs add latency for inspection
      - Status code spread: WAFs produce varied codes across probes
      - Block rate: % of probes that resulted in block-like responses
      - Header volatility: headers that change across probe responses
    """

    def analyse(self, baseline: ProbeResult, probe_results: list) -> list:
        signals = []

        valid_results = [r for r in probe_results if not r.error and r.status_code > 0]
        if len(valid_results) < 2:
            return signals

        baseline_len  = len(baseline.body_snippet)
        baseline_time = baseline.response_time
        baseline_status = baseline.status_code

        body_lengths   = [len(r.body_snippet) for r in valid_results]
        response_times = [r.response_time for r in valid_results]
        status_codes   = [r.status_code for r in valid_results]

        # ── Body length delta ─────────────────────────────────────────────────
        if baseline_len > 0:
            avg_probe_len = sum(body_lengths) / len(body_lengths)
            delta_ratio   = abs(avg_probe_len - baseline_len) / max(baseline_len, 1)
            if delta_ratio > 0.4:   # body changed by >40% on average
                signals.append(DetectionSignal(
                    layer="behavioral",
                    signal_type="body_delta",
                    detail=f"Body length changed significantly vs baseline "
                           f"(baseline={baseline_len}B, avg probe={int(avg_probe_len)}B, "
                           f"delta={int(delta_ratio*100)}%)",
                    matched_waf=None,
                    confidence_contribution=20,
                ))

        # ── Response time spike ───────────────────────────────────────────────
        if baseline_time > 0 and response_times:
            avg_probe_time = sum(response_times) / len(response_times)
            time_ratio = avg_probe_time / baseline_time
            if time_ratio > 2.5:   # probes take 2.5x longer than baseline
                signals.append(DetectionSignal(
                    layer="behavioral",
                    signal_type="timing",
                    detail=f"Response time spike on probes "
                           f"(baseline={baseline_time}s, avg probe={avg_probe_time:.2f}s, "
                           f"ratio={time_ratio:.1f}x) — suggests deep inspection",
                    matched_waf=None,
                    confidence_contribution=20,
                ))

        # ── Block rate ────────────────────────────────────────────────────────
        block_count = sum(1 for s in status_codes if s in BLOCK_STATUS_CODES)
        block_rate  = block_count / len(valid_results)
        if block_rate >= 0.3:      # 30%+ of probes got blocked
            contrib = int(block_rate * 40)  # scales up to 40 pts
            signals.append(DetectionSignal(
                layer="behavioral",
                signal_type="block_rate",
                detail=f"{block_count}/{len(valid_results)} probes blocked "
                       f"({int(block_rate*100)}% block rate)",
                matched_waf=None,
                confidence_contribution=min(contrib, 40),
            ))

        # ── Status code variance ──────────────────────────────────────────────
        unique_codes = set(status_codes)
        if len(unique_codes) >= 3:
            signals.append(DetectionSignal(
                layer="behavioral",
                signal_type="status_variance",
                detail=f"High status code variance across probes: {sorted(unique_codes)} "
                       "— WAF differentiating request types",
                matched_waf=None,
                confidence_contribution=15,
            ))

        # ── Consistent size mismatch on blocked requests ──────────────────────
        blocked_sizes = [len(r.body_snippet) for r in valid_results
                         if r.status_code in BLOCK_STATUS_CODES]
        if len(blocked_sizes) >= 2:
            size_variance = max(blocked_sizes) - min(blocked_sizes)
            if size_variance < 50:   # blocked pages are near-identical → templated block page
                signals.append(DetectionSignal(
                    layer="behavioral",
                    signal_type="templated_block",
                    detail=f"Blocked responses have near-identical body sizes "
                           f"(range: {min(blocked_sizes)}-{max(blocked_sizes)}B) "
                           "— strong indicator of WAF block template",
                    matched_waf=None,
                    confidence_contribution=35,
                ))

        return signals


# ─────────────────────────────────────────────────────────────────────────────
# LAYER 4 — CONFIDENCE SCORING ENGINE
# ─────────────────────────────────────────────────────────────────────────────
class ConfidenceEngine:
    """
    Aggregates all signals into a final confidence score.

    Scoring rules:
      - Signals from multiple independent layers add more confidence than
        repeated signals from the same layer
      - Specific WAF name matches contribute more than generic signals
      - Score is capped at 100
      - Verdict bands:
          0-20  : No WAF detected
          21-40 : Possibly a WAF (low confidence)
          41-65 : WAF likely present
          66-85 : WAF detected (high confidence)
          86-100: WAF confirmed (very high confidence)
    """

    def compute(self, signals: list) -> tuple:
        """Returns (score: int, waf_names: list, verdict: str)"""
        if not signals:
            return 0, [], "No WAF detected"

        # Deduplicate: one signal type per layer per WAF (avoid score inflation)
        seen = set()
        deduped = []
        for s in signals:
            key = (s.layer, s.signal_type, s.matched_waf or "generic")
            if key not in seen:
                seen.add(key)
                deduped.append(s)

        # Layer diversity bonus: signals from 2+ layers add 10pt bonus each
        layers_present = {s.layer for s in deduped}
        layer_bonus    = max(0, (len(layers_present) - 1) * 10)

        raw_score = sum(s.confidence_contribution for s in deduped) + layer_bonus
        score     = min(100, raw_score)

        # Collect WAF names (de-duplicated, sorted by frequency)
        name_counts = {}
        for s in deduped:
            if s.matched_waf:
                name_counts[s.matched_waf] = name_counts.get(s.matched_waf, 0) + 1
        waf_names = sorted(name_counts, key=lambda k: -name_counts[k])

        # Verdict
        if score <= 20:
            verdict = "No WAF detected"
        elif score <= 40:
            verdict = "Possibly a WAF (low confidence) — manual inspection recommended"
        elif score <= 65:
            verdict = "WAF likely present"
        elif score <= 85:
            verdict = "WAF detected (high confidence)"
        else:
            verdict = "WAF confirmed (very high confidence)"

        return score, waf_names, verdict


# ─────────────────────────────────────────────────────────────────────────────
# MAIN SCANNER ORCHESTRATOR
# ─────────────────────────────────────────────────────────────────────────────
class WAFScanner:
    """
    Orchestrates all four detection layers and produces a DetectionReport.
    """

    def __init__(self, target: str, timeout: int = DEFAULT_TIMEOUT,
                 verify_ssl: bool = False, proxy: Optional[str] = None,
                 skip_active: bool = False, verbose: bool = False):
        self.target      = self._normalise_url(target)
        self.skip_active = skip_active
        self.verbose     = verbose
        self.client      = HTTPClient(timeout=timeout, verify_ssl=verify_ssl,
                                       proxy=proxy, delay=not skip_active)
        self.passive     = PassiveDetector()
        self.behavioral  = BehavioralAnalyzer()
        self.scorer      = ConfidenceEngine()

    @staticmethod
    def _normalise_url(url: str) -> str:
        url = url.strip()
        if not url.startswith(("http://", "https://")):
            url = "https://" + url
        return url.rstrip("/")

    def scan(self) -> DetectionReport:
        from datetime import datetime, timezone
        report = DetectionReport(
            target=self.target,
            scan_time=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            waf_detected=False,
        )

        all_signals: list = []

        # ── Baseline request (normal GET /) ───────────────────────────────────
        _print_info(f"[1/4] Sending baseline request to {self.target} ...")
        baseline = self.client.get(self.target)

        if baseline.error and baseline.status_code == 0:
            _print_error(f"Baseline request failed: {baseline.error}")
            report.verdict = f"Scan failed: {baseline.error}"
            return report

        report.baseline = {
            "status_code": baseline.status_code,
            "response_time": baseline.response_time,
            "body_length": len(baseline.body_snippet),
            "server": baseline.headers.get("Server", baseline.headers.get("server", "N/A")),
        }
        report.raw_headers = baseline.headers
        _print_ok(f"   Baseline: HTTP {baseline.status_code}, "
                  f"{len(baseline.body_snippet)}B body, "
                  f"{baseline.response_time}s")

        # ── Layer 1: Passive fingerprinting ───────────────────────────────────
        _print_info("[2/4] Running passive fingerprinting ...")
        passive_signals = self.passive.analyse(baseline)
        all_signals.extend(passive_signals)
        _print_ok(f"   Passive signals found: {len(passive_signals)}")

        # ── Layer 2: Active probing ────────────────────────────────────────────
        probe_results = []
        if self.skip_active:
            _print_dim("[3/4] Active probing SKIPPED (--passive-only flag set)")
        else:
            _print_info(f"[3/4] Running {len(PROBE_PAYLOADS)} active probes "
                        f"(rate-limited, {MIN_DELAY}-{MAX_DELAY}s delays) ...")
            active_detector = ActiveDetector(self.client, self.target, self.verbose)
            active_signals, probe_results = active_detector.run_probes(baseline)
            all_signals.extend(active_signals)
            _print_ok(f"   Active signals found: {len(active_signals)}")

        # ── Layer 3: Behavioral analysis ──────────────────────────────────────
        _print_info("[4/4] Running behavioral analysis ...")
        if probe_results:
            behavioral_signals = self.behavioral.analyse(baseline, probe_results)
            all_signals.extend(behavioral_signals)
            _print_ok(f"   Behavioral signals found: {len(behavioral_signals)}")

            # Probe summary stats
            valid_pr = [r for r in probe_results if not r.error and r.status_code > 0]
            if valid_pr:
                report.probe_summary = {
                    "total_probes": len(PROBE_PAYLOADS),
                    "successful_probes": len(valid_pr),
                    "blocked_probes": sum(1 for r in valid_pr if r.status_code in BLOCK_STATUS_CODES),
                    "avg_response_time": round(
                        sum(r.response_time for r in valid_pr) / len(valid_pr), 3),
                    "status_codes_seen": sorted(set(r.status_code for r in valid_pr)),
                }
        else:
            _print_dim("   Behavioral analysis skipped (no probe data)")

        # ── Score and finalise ─────────────────────────────────────────────────
        score, waf_names, verdict = self.scorer.compute(all_signals)
        report.confidence   = score
        report.waf_names    = waf_names
        report.verdict      = verdict
        report.waf_detected = score > 20
        report.signals      = [asdict(s) for s in all_signals]
        report.recommendations = self._make_recommendations(score, waf_names, all_signals)

        return report

    def _make_recommendations(self, score: int, waf_names: list, signals: list) -> list:
        recs = []
        if score > 20:
            recs.append("A WAF/firewall is likely protecting this target. Consider evasion techniques "
                        "or out-of-band testing before active exploitation attempts.")
        if any(s.get("signal_type") == "timing" for s in [asdict(x) for x in signals]):
            recs.append("Response time spikes detected — the WAF may be performing deep packet inspection. "
                        "Slow down attack timing significantly.")
        if "Cloudflare" in waf_names:
            recs.append("Cloudflare detected: look for origin IP leaks via DNS history, "
                        "Shodan, or Certificate Transparency logs to bypass the CDN layer.")
        if "AWS WAF / CloudFront" in waf_names:
            recs.append("AWS WAF detected: check for misconfigured S3 buckets or API Gateway "
                        "endpoints that may bypass WAF rules.")
        if score <= 20:
            recs.append("No WAF detected. The target may be directly accessible, "
                        "or using a custom/unknown firewall solution.")
        return recs


# ─────────────────────────────────────────────────────────────────────────────
# OUTPUT / DISPLAY HELPERS
# ─────────────────────────────────────────────────────────────────────────────
def _c(text: str, code: str) -> str:
    """ANSI colour wrapper — degrades gracefully on Windows without colour support."""
    if sys.platform == "win32":
        try:
            import ctypes
            ctypes.windll.kernel32.SetConsoleMode(
                ctypes.windll.kernel32.GetStdHandle(-11), 7)
        except Exception:
            return text
    return f"\033[{code}m{text}\033[0m"

def _print_info(msg):  print(_c(f"[*] {msg}", "94"))
def _print_ok(msg):    print(_c(f"[+] {msg}", "92"))
def _print_yellow(msg):print(_c(f"[!] {msg}", "93"))
def _print_error(msg): print(_c(f"[✗] {msg}", "91"))
def _print_dim(msg):   print(_c(f"    {msg}", "90"))


def print_banner():
    banner = """
  +--------------------------------------------------+
  |   waf00 v{version:<10}                           |
  |   Advanced WAF / Firewall Detection Tool         |
  |   4-layer: Passive | Active | Behavioral | Score |
  +--------------------------------------------------+
""".format(version=VERSION)
    print(_c(banner, "96"))


def print_report(report: DetectionReport, verbose: bool = False):
    print()
    print(_c("=" * 60, "90"))
    print(_c("  DETECTION REPORT", "1"))
    print(_c("=" * 60, "90"))
    print(f"  Target     : {report.target}")
    print(f"  Scan time  : {report.scan_time}")
    print()

    # Confidence bar
    bar_len  = 40
    filled   = int(report.confidence / 100 * bar_len)
    bar      = "#" * filled + "-" * (bar_len - filled)
    if report.confidence >= 66:
        bar_color = "91"   # red
    elif report.confidence >= 41:
        bar_color = "93"   # yellow
    else:
        bar_color = "92"   # green
    print(f"  Confidence : {_c(bar, bar_color)} {report.confidence}%")
    print()

    if report.waf_detected:
        if report.waf_names:
            print(_c(f"  [!] WAF/Firewall DETECTED", "91"))
            print(f"  Identified : {', '.join(report.waf_names)}")
        else:
            print(_c(f"  [!] WAF/Firewall DETECTED (vendor unknown)", "93"))
    else:
        print(_c("  [OK] No WAF detected", "92"))

    print(f"  Verdict    : {report.verdict}")
    print()

    # Baseline info
    if report.baseline:
        b = report.baseline
        print(_c("  -- Baseline ------------------------------------------", "90"))
        print(f"  Status     : HTTP {b.get('status_code')}")
        print(f"  Server     : {b.get('server')}")
        print(f"  Body size  : {b.get('body_length')}B")
        print(f"  Resp time  : {b.get('response_time')}s")
        print()

    # Probe summary
    if report.probe_summary:
        ps = report.probe_summary
        print(_c("  -- Active Probe Summary ------------------------------", "90"))
        print(f"  Probes sent    : {ps.get('total_probes')}")
        print(f"  Successful     : {ps.get('successful_probes')}")
        print(f"  Blocked        : {ps.get('blocked_probes')}")
        print(f"  Avg resp time  : {ps.get('avg_response_time')}s")
        print(f"  Status codes   : {ps.get('status_codes_seen')}")
        print()

    # Signals
    if verbose and report.signals:
        print(_c("  -- Detection Signals ---------------------------------", "90"))
        for s in report.signals:
            layer_color = {"passive": "94", "active": "93", "behavioral": "95"}.get(s["layer"], "97")
            waf_tag = f"[{s['matched_waf']}]" if s["matched_waf"] else "[generic]"
            layer_tag = "[{}]".format(s["layer"])
            print(f"  {_c(layer_tag, layer_color)} "
                  f"{_c(waf_tag, '96')} "
                  f"+{s['confidence_contribution']}pt -- {s['detail']}")
        print()

    # Recommendations
    if report.recommendations:
        print(_c("  -- Recommendations -----------------------------------", "90"))
        for i, rec in enumerate(report.recommendations, 1):
            print(f"  {i}. {rec}")
        print()

    print(_c("=" * 60, "90"))
    print()


# ─────────────────────────────────────────────────────────────────────────────
# CLI ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog=TOOL_NAME,
        description="Advanced multi-layer WAF/Firewall detection tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python waf00.py https://example.com
  python waf00.py example.com -v
  python waf00.py https://target.com --passive-only
  python waf00.py https://target.com --report results.json
  python waf00.py https://target.com --proxy http://127.0.0.1:8080
  python waf00.py https://target.com --timeout 15 -v --report out.json
        """,
    )
    p.add_argument("target", help="Target URL or domain (e.g. https://example.com or example.com)")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="Show all detection signals in the report")
    p.add_argument("--passive-only", action="store_true",
                   help="Only run passive fingerprinting (no active probes sent)")
    p.add_argument("--report", metavar="FILE",
                   help="Save full JSON report to this file path")
    p.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT,
                   help=f"HTTP request timeout in seconds (default: {DEFAULT_TIMEOUT})")
    p.add_argument("--proxy", metavar="URL",
                   help="HTTP/HTTPS proxy URL (e.g. http://127.0.0.1:8080)")
    p.add_argument("--no-ssl-verify", action="store_true",
                   help="Disable SSL certificate verification")
    p.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    return p


def main():
    print_banner()
    parser = build_parser()
    args   = parser.parse_args()

    _print_info(f"Target  : {args.target}")
    if args.passive_only:
        _print_yellow("Mode    : Passive only (no active probes)")
    else:
        _print_info(f"Mode    : Full scan ({len(PROBE_PAYLOADS)} active probes + passive + behavioral)")
    if args.proxy:
        _print_info(f"Proxy   : {args.proxy}")
    print()

    scanner = WAFScanner(
        target=args.target,
        timeout=args.timeout,
        verify_ssl=not args.no_ssl_verify,
        proxy=args.proxy,
        skip_active=args.passive_only,
        verbose=args.verbose,
    )

    try:
        report = scanner.scan()
    except KeyboardInterrupt:
        print()
        _print_error("Scan interrupted by user.")
        sys.exit(1)

    print_report(report, verbose=args.verbose)

    # Save JSON report
    if args.report:
        try:
            report_dict = asdict(report)
            with open(args.report, "w", encoding="utf-8") as f:
                json.dump(report_dict, f, indent=2)
            _print_ok(f"JSON report saved to: {args.report}")
        except Exception as e:
            _print_error(f"Failed to save report: {e}")

    # Exit code: 1 if WAF detected, 0 if not (useful in scripts/CI)
    sys.exit(1 if report.waf_detected else 0)


if __name__ == "__main__":
    main()
